import { EmailNotification } from '@servicenow/sdk/core'

// Replaces the legacy SendStatusMail agent. All notifications are event-driven so the same
// business rules that enforce the lifecycle also decide when mail is sent.

export const caseStageChangedNotification = EmailNotification({
    $id: Now.ID['ntf_case_stage_changed'],
    table: 'x_cog_mah_awards_case',
    name: 'MAH Awards case stage changed',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah.case.stage_changed',
        item: 'event.parm1',
    },
    recipientDetails: {
        recipientFields: ['assigned_to', 'requester.email'],
        sendToCreator: false,
        isSubscribableByAllUsers: false,
    },
    emailContent: {
        subject: 'Awards case ${number} is now ${stage}',
        importance: 'low',
        messageHtml: `<p>Awards case <strong>\${number}</strong> for \${requester.last_name}, \${requester.first_name} has moved to the <strong>\${stage}</strong> stage.</p>
<table cellpadding="4">
<tr><td>Source agency</td><td>\${source_agency}</td></tr>
<tr><td>Authorization date</td><td>\${authorization_date}</td></tr>
<tr><td>Award lines</td><td>\${line_count} (\${total_quantity} items)</td></tr>
<tr><td>Assigned to</td><td>\${assigned_to}</td></tr>
<tr><td>Days in previous stage</td><td>\${days_in_stage}</td></tr>
</table>
<p>This message was generated by MAH Case Management. It contains no personally identifiable information beyond the requester name. Do not reply.</p>`,
    },
})

export const caseAgingRedNotification = EmailNotification({
    $id: Now.ID['ntf_case_aging_red'],
    table: 'x_cog_mah_awards_case',
    name: 'MAH Awards case aging red (75 days)',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah.case.aging_red',
    },
    recipientDetails: {
        recipientFields: ['assigned_to', 'assignment_group'],
        sendToCreator: false,
    },
    emailContent: {
        subject: 'ACTION REQUIRED: Awards case ${number} has exceeded 75 days in ${stage}',
        importance: 'high',
        messageHtml: `<p>Awards case <strong>\${number}</strong> has been in the <strong>\${stage}</strong> stage for <strong>\${days_in_stage}</strong> days, exceeding the 75-day ceiling.</p>
<p>Requester: \${requester.last_name}, \${requester.first_name} (\${requester.type})<br/>
Source agency: \${source_agency}<br/>
Assigned to: \${assigned_to}<br/>
Aging flag: \${aging_flag}</p>
<p>Please work or escalate this case. Generated by MAH Nightly Aging.</p>`,
    },
})

export const requestSubmittedNotification = EmailNotification({
    $id: Now.ID['ntf_request_submitted'],
    table: 'x_cog_mah_heraldry_request',
    name: 'MAH Heraldry request submitted',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah.request.submitted',
    },
    recipientDetails: {
        recipientFields: ['submitted_by', 'reviewer'],
        eventParm1WithRecipient: true,
        sendToCreator: false,
    },
    emailContent: {
        subject: 'DD Form 1348-6 request ${number} (${document_number}) submitted',
        messageHtml: `<p>Heraldry request <strong>\${number}</strong> has been submitted for review.</p>
<table cellpadding="4">
<tr><td>Document number</td><td>\${document_number}</td></tr>
<tr><td>DODAAC / UIC</td><td>\${dodaac} / \${uic}</td></tr>
<tr><td>Requisition priority</td><td>\${requisition_priority}</td></tr>
<tr><td>Requesting unit</td><td>\${requesting_unit}</td></tr>
<tr><td>Lines / total</td><td>\${line_count} / $\${total_extended_price}</td></tr>
</table>`,
    },
})

export const requestReleasedNotification = EmailNotification({
    $id: Now.ID['ntf_request_released'],
    table: 'x_cog_mah_heraldry_request',
    name: 'MAH Heraldry request released to vendor',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah.request.released',
    },
    recipientDetails: {
        recipientFields: ['vendor.portal_user', 'vendor.email', 'submitted_by', 'released_by'],
        sendToCreator: false,
    },
    emailContent: {
        subject: 'Heraldry request ${number} released to ${vendor.name}',
        importance: 'high',
        messageHtml: `<p>Request <strong>\${number}</strong> (document \${document_number}) has been released to <strong>\${vendor.name}</strong> (CAGE \${vendor.cage_code}) on \${released_to_vendor}.</p>
<p>Required delivery date: \${required_delivery_date}<br/>
Ship to: \${ship_to}<br/>
Lines: \${line_count}, extended total: $\${total_extended_price}</p>
<p>The request is now locked. Vendor acknowledgement, ship date and tracking may be recorded through the vendor portal.</p>`,
    },
})

export const sesSubmittedNotification = EmailNotification({
    $id: Now.ID['ntf_ses_submitted'],
    table: 'x_cog_mah_ses_flag_request',
    name: 'MAH SES flag request submitted',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah.ses.submitted',
    },
    recipientDetails: {
        eventParm1WithRecipient: true,
        recipientFields: ['submitted_by'],
        sendToCreator: false,
    },
    emailContent: {
        subject: 'SES flag request ${number} received for ${executive_name}',
        messageHtml: `<p>Your Senior Executive Service flag request <strong>\${number}</strong> has been received by TACOM ILSC Medals, Awards & Heraldry.</p>
<p>Executive: \${executive_name}, \${position_title}<br/>
Requesting office: \${requesting_office}<br/>
Flag type / quantity: \${flag_type} / \${quantity}</p>
<p>You will be notified when the request is approved and shipped.</p>`,
    },
})
