// GENERATED FILE - do not edit by hand.
// Source of truth: src/server/lib/legacyContract.ts (+ statusMap.ts, rowTransforms.ts). Regenerate with `npm run gen:migration`.
// Orphans and journal rows without a parent are left as Import Set rows in state `error` (no custom exception table).
import { ImportSet } from '@servicenow/sdk/core'

export const tm_vendor = ImportSet({
    $id: Now.ID['tm_vendor'],
    name: 'MAH Vendor -> core_company',
    sourceTable: 'x_cog_mah_native_stg_vendor',
    targetTable: 'core_company',
    active: true,
    order: 10,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        x_cog_mah_native_legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        name: { sourceField: 'vendor_name' },
        x_cog_mah_native_cage_code: { sourceField: 'vendor_key' },
        x_cog_mah_native_contract_number: { sourceField: 'contract_number' },
        x_cog_mah_native_poc: { sourceField: 'poc' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_vendor_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('Vendor', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_vendor_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('Vendor', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_vendor_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('Vendor', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_vendor_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('Vendor', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_heraldic_item = ImportSet({
    $id: Now.ID['tm_heraldic_item'],
    name: 'MAH HeraldicItem -> x_cog_mah_native_catalog_item',
    sourceTable: 'x_cog_mah_native_stg_heraldic_item',
    targetTable: 'x_cog_mah_native_catalog_item',
    active: true,
    order: 20,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        model_number: { sourceField: 'stock_number' },
        name: { sourceField: 'item_name' },
        fsc: { sourceField: 'fsc' },
        niin: { sourceField: 'niin' },
        branch: { sourceField: 'branch' },
        reference: { sourceField: 'reference' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_heraldic_item_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('HeraldicItem', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_heraldic_item_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('HeraldicItem', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_heraldic_item_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('HeraldicItem', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_heraldic_item_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('HeraldicItem', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_requester = ImportSet({
    $id: Now.ID['tm_requester'],
    name: 'MAH Requester -> x_cog_mah_native_requester',
    sourceTable: 'x_cog_mah_native_stg_requester',
    targetTable: 'x_cog_mah_native_requester',
    active: true,
    order: 30,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_number: { sourceField: 'requester_id' },
        first_name: { sourceField: 'first_name' },
        last_name: { sourceField: 'last_name' },
        city: { sourceField: 'city' },
        zip: { sourceField: 'zip' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_requester_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('Requester', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_requester_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('Requester', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_requester_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('Requester', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_requester_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('Requester', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_unit_requester = ImportSet({
    $id: Now.ID['tm_unit_requester'],
    name: 'MAH HeraldryRequester -> x_cog_mah_native_requester',
    sourceTable: 'x_cog_mah_native_stg_unit_requester',
    targetTable: 'x_cog_mah_native_requester',
    active: true,
    order: 35,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_number: { sourceField: 'requester_key' },
        name: { sourceField: 'name' },
        unit_name: { sourceField: 'unit_name' },
        rank: { sourceField: 'rank' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_unit_requester_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('HeraldryRequester', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_unit_requester_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('HeraldryRequester', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_unit_requester_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('HeraldryRequester', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_unit_requester_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('HeraldryRequester', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_authorization_file = ImportSet({
    $id: Now.ID['tm_authorization_file'],
    name: 'MAH AuthorizationFile -> x_cog_mah_native_authorization_file',
    sourceTable: 'x_cog_mah_native_stg_authorization_file',
    targetTable: 'x_cog_mah_native_authorization_file',
    active: true,
    order: 40,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        file_name: { sourceField: 'file_name' },
        legacy_number: { sourceField: 'file_key' },
        layout: { sourceField: 'layout' },
        source_hash: { sourceField: 'trailer_checksum' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_authorization_file_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('AuthorizationFile', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_authorization_file_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('AuthorizationFile', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_authorization_file_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('AuthorizationFile', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_authorization_file_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('AuthorizationFile', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_awards_case = ImportSet({
    $id: Now.ID['tm_awards_case'],
    name: 'MAH AwardsCase -> x_cog_mah_native_awards_case',
    sourceTable: 'x_cog_mah_native_stg_awards_case',
    targetTable: 'x_cog_mah_native_awards_case',
    active: true,
    order: 50,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_number: { sourceField: 'case_number' },
        veteran_last_name: { sourceField: 'veteran_last_name' },
        veteran_first_name: { sourceField: 'veteran_first_name' },
        pick_bin: { sourceField: 'pick_bin' },
        ship_to_name: { sourceField: 'ship_to_name' },
        ship_to_city: { sourceField: 'ship_to_city' },
        ship_to_zip: { sourceField: 'ship_to_zip' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_awards_case_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('AwardsCase', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_awards_case_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('AwardsCase', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_awards_case_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('AwardsCase', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_awards_case_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('AwardsCase', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_award_line = ImportSet({
    $id: Now.ID['tm_award_line'],
    name: 'MAH AwardLine -> x_cog_mah_native_award_line',
    sourceTable: 'x_cog_mah_native_stg_award_line',
    targetTable: 'x_cog_mah_native_award_line',
    active: true,
    order: 60,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_award_name: { sourceField: 'award_name' },
        legacy_award_code: { sourceField: 'award_code' },
        set_type: { sourceField: 'set_type' },
        stock_number: { sourceField: 'stock_number' },
        authority: { sourceField: 'authority' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_award_line_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('AwardLine', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_award_line_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('AwardLine', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_award_line_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('AwardLine', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_award_line_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('AwardLine', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_engraving_job = ImportSet({
    $id: Now.ID['tm_engraving_job'],
    name: 'MAH EngravingJob -> x_cog_mah_native_engraving_job',
    sourceTable: 'x_cog_mah_native_stg_engraving_job',
    targetTable: 'x_cog_mah_native_engraving_job',
    active: true,
    order: 70,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_number: { sourceField: 'job_number' },
        machine: { sourceField: 'machine' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_engraving_job_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('EngravingJob', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_engraving_job_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('EngravingJob', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_engraving_job_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('EngravingJob', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_engraving_job_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('EngravingJob', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_shipment = ImportSet({
    $id: Now.ID['tm_shipment'],
    name: 'MAH ShipmentRecord -> x_cog_mah_native_shipment',
    sourceTable: 'x_cog_mah_native_stg_shipment',
    targetTable: 'x_cog_mah_native_shipment',
    active: true,
    order: 80,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_number: { sourceField: 'shipment_number' },
        tracking_number: { sourceField: 'tracking_number' },
        contents: { sourceField: 'contents' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_shipment_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('ShipmentRecord', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_shipment_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('ShipmentRecord', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_shipment_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('ShipmentRecord', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_shipment_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('ShipmentRecord', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_case_note = ImportSet({
    $id: Now.ID['tm_case_note'],
    name: 'MAH CaseNote -> x_cog_mah_native_awards_case',
    sourceTable: 'x_cog_mah_native_stg_case_note',
    targetTable: 'x_cog_mah_native_awards_case',
    active: true,
    order: 90,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: false,
    fields: {
        legacy_unid: { sourceField: 'parent_unid', coalesce: true, coalesceCaseSensitive: false },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_case_note_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('CaseNote', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_case_note_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('CaseNote', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_case_note_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('CaseNote', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_case_note_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('CaseNote', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_heraldry_request = ImportSet({
    $id: Now.ID['tm_heraldry_request'],
    name: 'MAH Request -> x_cog_mah_native_heraldry_request',
    sourceTable: 'x_cog_mah_native_stg_heraldry_request',
    targetTable: 'x_cog_mah_native_heraldry_request',
    active: true,
    order: 100,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        document_number: { sourceField: 'document_number' },
        dodaac: { sourceField: 'dodaac' },
        uic: { sourceField: 'uic' },
        project_code: { sourceField: 'project_code' },
        fund_code: { sourceField: 'fund_code' },
        signal_code: { sourceField: 'signal_code' },
        requesting_unit: { sourceField: 'unit_name' },
        request_type: { sourceField: 'request_type' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_heraldry_request_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('Request', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_heraldry_request_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('Request', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_heraldry_request_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('Request', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_heraldry_request_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('Request', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_request_line = ImportSet({
    $id: Now.ID['tm_request_line'],
    name: 'MAH RequestLine -> x_cog_mah_native_request_line',
    sourceTable: 'x_cog_mah_native_stg_request_line',
    targetTable: 'x_cog_mah_native_request_line',
    active: true,
    order: 110,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        nomenclature: { sourceField: 'item_description' },
        line_document_number: { sourceField: 'line_doc_number' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_request_line_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('RequestLine', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_request_line_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('RequestLine', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_request_line_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('RequestLine', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_request_line_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('RequestLine', import_set);\n})(source, map, log, target);",
        },
    ],
})

export const tm_ses_flag_request = ImportSet({
    $id: Now.ID['tm_ses_flag_request'],
    name: 'MAH SESFlagRequest -> x_cog_mah_native_ses_flag_request',
    sourceTable: 'x_cog_mah_native_stg_ses_flag_request',
    targetTable: 'x_cog_mah_native_ses_flag_request',
    active: true,
    order: 120,
    runBusinessRules: false,
    enforceMandatoryFields: 'no',
    copyEmptyFields: false,
    createOnEmptyCoalesce: true,
    fields: {
        legacy_unid: { sourceField: 'unid', coalesce: true, coalesceCaseSensitive: false },
        legacy_number: { sourceField: 'ses_flag_number' },
        executive_name: { sourceField: 'executive_name' },
        position_title: { sourceField: 'executive_title' },
        requesting_office: { sourceField: 'organization' },
        legacy_flag_type: { sourceField: 'flag_type' },
    },
    runScript: false,
    scripts: [
        {
            $id: Now.ID['tm_ses_flag_request_onStart'],
            when: 'onStart',
            order: 100,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onStart('SESFlagRequest', import_set);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_ses_flag_request_onBefore'],
            when: 'onBefore',
            order: 200,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    var r = new x_cog_mah_native.MAHNativeMigration().onBefore('SESFlagRequest', source, target, action == 'update');\n    if (r.ignore) { ignore = true; }\n    if (r.error) { error = true; error_message = r.statusMessage; }\n    if (r.statusMessage) { status_message = r.statusMessage; }\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_ses_flag_request_onAfter'],
            when: 'onAfter',
            order: 300,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onAfter('SESFlagRequest', source, target);\n})(source, map, log, target);",
        },
        {
            $id: Now.ID['tm_ses_flag_request_onComplete'],
            when: 'onComplete',
            order: 400,
            active: true,
            script: "(function runTransformScript(source, map, log, target) {\n    new x_cog_mah_native.MAHNativeMigration().onComplete('SESFlagRequest', import_set);\n})(source, map, log, target);",
        },
    ],
})
