// GENERATED FILE - do not edit by hand.
// Source of truth: src/server/lib/legacyContract.ts (+ statusMap.ts, rowTransforms.ts). Regenerate with `npm run gen:migration`.
import { Table, StringColumn } from '@servicenow/sdk/core'

/** heraldry-Vendor.csv → x_cog_mah_vendor (load order 10). */
export const x_cog_mah_stg_vendor = Table({
    name: 'x_cog_mah_stg_vendor',
    label: 'MAH Staging: heraldry Vendor',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        vendor_key: StringColumn({ label: 'VendorKey', maxLength: 255 }),
        vendor_name: StringColumn({ label: 'VendorName', maxLength: 255 }),
        address: StringColumn({ label: 'Address', maxLength: 255 }),
        city: StringColumn({ label: 'City', maxLength: 255 }),
        state: StringColumn({ label: 'State', maxLength: 255 }),
        zip: StringColumn({ label: 'ZIP', maxLength: 255 }),
        poc: StringColumn({ label: 'POC', maxLength: 255 }),
        phone: StringColumn({ label: 'Phone', maxLength: 255 }),
        email: StringColumn({ label: 'Email', maxLength: 255 }),
        products: StringColumn({ label: 'Products', maxLength: 255 }),
        contract_number: StringColumn({ label: 'ContractNumber', maxLength: 255 }),
        lead_time_days: StringColumn({ label: 'LeadTimeDays', maxLength: 255 }),
        active: StringColumn({ label: 'Active', maxLength: 255 }),
        vendor_users: StringColumn({ label: 'VendorUsers', maxLength: 255 }),
        vendor_group: StringColumn({ label: 'VendorGroup', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** heraldry-HeraldicItem.csv → x_cog_mah_heraldic_item (load order 20). */
export const x_cog_mah_stg_heraldic_item = Table({
    name: 'x_cog_mah_stg_heraldic_item',
    label: 'MAH Staging: heraldry HeraldicItem',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        stock_number: StringColumn({ label: 'StockNumber', maxLength: 255 }),
        item_name: StringColumn({ label: 'ItemName', maxLength: 255 }),
        category: StringColumn({ label: 'Category', maxLength: 255 }),
        description: StringColumn({ label: 'Description', maxLength: 4000 }),
        branch: StringColumn({ label: 'Branch', maxLength: 255 }),
        unit_of_issue: StringColumn({ label: 'UnitOfIssue', maxLength: 255 }),
        unit_price: StringColumn({ label: 'UnitPrice', maxLength: 255 }),
        max_qty_per_request: StringColumn({ label: 'MaxQtyPerRequest', maxLength: 255 }),
        lead_time_days: StringColumn({ label: 'LeadTimeDays', maxLength: 255 }),
        approved_vendors: StringColumn({ label: 'ApprovedVendors', maxLength: 255 }),
        reference: StringColumn({ label: 'Reference', maxLength: 255 }),
        active: StringColumn({ label: 'Active', maxLength: 255 }),
        fsc: StringColumn({ label: 'FSC', maxLength: 255 }),
        niin: StringColumn({ label: 'NIIN', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-Requester.csv → x_cog_mah_requester (load order 30). */
export const x_cog_mah_stg_requester = Table({
    name: 'x_cog_mah_stg_requester',
    label: 'MAH Staging: vetmedals Requester',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        requester_id: StringColumn({ label: 'RequesterID', maxLength: 255 }),
        last_name: StringColumn({ label: 'LastName', maxLength: 255 }),
        suffix: StringColumn({ label: 'Suffix', maxLength: 255 }),
        first_name: StringColumn({ label: 'FirstName', maxLength: 255 }),
        mi: StringColumn({ label: 'MI', maxLength: 255 }),
        relationship: StringColumn({ label: 'Relationship', maxLength: 255 }),
        veteran_name: StringColumn({ label: 'VeteranName', maxLength: 255 }),
        street: StringColumn({ label: 'Street', maxLength: 255 }),
        city: StringColumn({ label: 'City', maxLength: 255 }),
        state: StringColumn({ label: 'State', maxLength: 255 }),
        zip: StringColumn({ label: 'ZIP', maxLength: 255 }),
        phone: StringColumn({ label: 'Phone', maxLength: 255 }),
        email: StringColumn({ label: 'Email', maxLength: 255 }),
        preferred_contact: StringColumn({ label: 'PreferredContact', maxLength: 255 }),
        source: StringColumn({ label: 'Source', maxLength: 255 }),
        created_date: StringColumn({ label: 'CreatedDate', maxLength: 255 }),
        address_verified: StringColumn({ label: 'AddressVerified', maxLength: 255 }),
        address_verified_date: StringColumn({ label: 'AddressVerifiedDate', maxLength: 255 }),
        lookup_key: StringColumn({ label: 'LookupKey', maxLength: 255 }),
        display_name: StringColumn({ label: 'DisplayName', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        merged_into: StringColumn({ label: 'MergedInto', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** heraldry-Requester.csv → x_cog_mah_requester (load order 35). */
export const x_cog_mah_stg_unit_requester = Table({
    name: 'x_cog_mah_stg_unit_requester',
    label: 'MAH Staging: heraldry Requester',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        requester_key: StringColumn({ label: 'RequesterKey', maxLength: 255 }),
        name: StringColumn({ label: 'Name', maxLength: 255 }),
        rank: StringColumn({ label: 'Rank', maxLength: 255 }),
        dodaac: StringColumn({ label: 'DODAAC', maxLength: 255 }),
        uic: StringColumn({ label: 'UIC', maxLength: 255 }),
        unit_name: StringColumn({ label: 'UnitName', maxLength: 255 }),
        role: StringColumn({ label: 'Role', maxLength: 255 }),
        phone: StringColumn({ label: 'Phone', maxLength: 255 }),
        email: StringColumn({ label: 'Email', maxLength: 255 }),
        created_date: StringColumn({ label: 'CreatedDate', maxLength: 255 }),
        lookup_key: StringColumn({ label: 'LookupKey', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-AuthorizationFile.csv → x_cog_mah_authorization_file (load order 40). */
export const x_cog_mah_stg_authorization_file = Table({
    name: 'x_cog_mah_stg_authorization_file',
    label: 'MAH Staging: vetmedals AuthorizationFile',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        file_name: StringColumn({ label: 'FileName', maxLength: 255 }),
        source_agency: StringColumn({ label: 'SourceAgency', maxLength: 255 }),
        layout: StringColumn({ label: 'Layout', maxLength: 255 }),
        transmission_date: StringColumn({ label: 'TransmissionDate', maxLength: 255 }),
        received_date: StringColumn({ label: 'ReceivedDate', maxLength: 255 }),
        authorization_date: StringColumn({ label: 'AuthorizationDate', maxLength: 255 }),
        import_status: StringColumn({ label: 'ImportStatus', maxLength: 255 }),
        imported_date: StringColumn({ label: 'ImportedDate', maxLength: 255 }),
        imported_by: StringColumn({ label: 'ImportedBy', maxLength: 255 }),
        record_count: StringColumn({ label: 'RecordCount', maxLength: 255 }),
        cases_created: StringColumn({ label: 'CasesCreated', maxLength: 255 }),
        lines_created: StringColumn({ label: 'LinesCreated', maxLength: 255 }),
        requesters_created: StringColumn({ label: 'RequestersCreated', maxLength: 255 }),
        requesters_matched: StringColumn({ label: 'RequestersMatched', maxLength: 255 }),
        records_rejected: StringColumn({ label: 'RecordsRejected', maxLength: 255 }),
        trailer_checksum: StringColumn({ label: 'TrailerChecksum', maxLength: 255 }),
        checksum_match: StringColumn({ label: 'ChecksumMatch', maxLength: 255 }),
        import_log: StringColumn({ label: 'ImportLog', maxLength: 4000 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        file_key: StringColumn({ label: 'FileKey', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-AwardsCase.csv → x_cog_mah_awards_case (load order 50). */
export const x_cog_mah_stg_awards_case = Table({
    name: 'x_cog_mah_stg_awards_case',
    label: 'MAH Staging: vetmedals AwardsCase',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        case_number: StringColumn({ label: 'CaseNumber', maxLength: 255 }),
        stage: StringColumn({ label: 'Stage', maxLength: 255 }),
        source: StringColumn({ label: 'Source', maxLength: 255 }),
        auth_file_name: StringColumn({ label: 'AuthFileName', maxLength: 255 }),
        auth_file_line: StringColumn({ label: 'AuthFileLine', maxLength: 255 }),
        authorization_date: StringColumn({ label: 'AuthorizationDate', maxLength: 255 }),
        entered_date: StringColumn({ label: 'EnteredDate', maxLength: 255 }),
        entered_by: StringColumn({ label: 'EnteredBy', maxLength: 255 }),
        priority: StringColumn({ label: 'Priority', maxLength: 255 }),
        service_number: StringColumn({ label: 'ServiceNumber', maxLength: 255 }),
        veteran_last_name: StringColumn({ label: 'VeteranLastName', maxLength: 255 }),
        veteran_first_name: StringColumn({ label: 'VeteranFirstName', maxLength: 255 }),
        veteran_mi: StringColumn({ label: 'VeteranMI', maxLength: 255 }),
        veteran_rank: StringColumn({ label: 'VeteranRank', maxLength: 255 }),
        branch: StringColumn({ label: 'Branch', maxLength: 255 }),
        service_from: StringColumn({ label: 'ServiceFrom', maxLength: 255 }),
        service_to: StringColumn({ label: 'ServiceTo', maxLength: 255 }),
        era: StringColumn({ label: 'Era', maxLength: 255 }),
        deceased: StringColumn({ label: 'Deceased', maxLength: 255 }),
        requester_key: StringColumn({ label: 'RequesterKey', maxLength: 255 }),
        requester_name: StringColumn({ label: 'RequesterName', maxLength: 255 }),
        relationship: StringColumn({ label: 'Relationship', maxLength: 255 }),
        assigned_csr: StringColumn({ label: 'AssignedCSR', maxLength: 255 }),
        line_count: StringColumn({ label: 'LineCount', maxLength: 255 }),
        engraving_required: StringColumn({ label: 'EngravingRequired', maxLength: 255 }),
        engraving_date: StringColumn({ label: 'EngravingDate', maxLength: 255 }),
        engraving_job_number: StringColumn({ label: 'EngravingJobNumber', maxLength: 255 }),
        assembly_date: StringColumn({ label: 'AssemblyDate', maxLength: 255 }),
        qc_result: StringColumn({ label: 'QCResult', maxLength: 255 }),
        warehouse_date: StringColumn({ label: 'WarehouseDate', maxLength: 255 }),
        pick_bin: StringColumn({ label: 'PickBin', maxLength: 255 }),
        shipped_date: StringColumn({ label: 'ShippedDate', maxLength: 255 }),
        tracking_number: StringColumn({ label: 'TrackingNumber', maxLength: 255 }),
        closed_date: StringColumn({ label: 'ClosedDate', maxLength: 255 }),
        days_open: StringColumn({ label: 'DaysOpen', maxLength: 255 }),
        aging_flag: StringColumn({ label: 'AgingFlag', maxLength: 255 }),
        hold_reason: StringColumn({ label: 'HoldReason', maxLength: 255 }),
        stage_before_hold: StringColumn({ label: 'StageBeforeHold', maxLength: 255 }),
        ship_to_name: StringColumn({ label: 'ShipToName', maxLength: 255 }),
        ship_to_street: StringColumn({ label: 'ShipToStreet', maxLength: 255 }),
        ship_to_city: StringColumn({ label: 'ShipToCity', maxLength: 255 }),
        ship_to_state: StringColumn({ label: 'ShipToState', maxLength: 255 }),
        ship_to_zip: StringColumn({ label: 'ShipToZIP', maxLength: 255 }),
        remarks: StringColumn({ label: 'Remarks', maxLength: 4000 }),
        status_history: StringColumn({ label: 'StatusHistory', maxLength: 4000 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        doc_authors: StringColumn({ label: 'DocAuthors', maxLength: 1000 }),
        lookup_key: StringColumn({ label: 'LookupKey', maxLength: 255 }),
        days_in_stage: StringColumn({ label: 'DaysInStage', maxLength: 255 }),
        last_modified_by: StringColumn({ label: 'LastModifiedBy', maxLength: 255 }),
        last_modified_date: StringColumn({ label: 'LastModifiedDate', maxLength: 255 }),
        aging_last_eval: StringColumn({ label: 'AgingLastEval', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-AwardLine.csv → x_cog_mah_award_line (load order 60). */
export const x_cog_mah_stg_award_line = Table({
    name: 'x_cog_mah_stg_award_line',
    label: 'MAH Staging: vetmedals AwardLine',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        parent_case_number: StringColumn({ label: 'ParentCaseNumber', maxLength: 255 }),
        parent_unid_2: StringColumn({ label: 'ParentUNID (ParentUNID_2)', maxLength: 255 }),
        veteran_name: StringColumn({ label: 'VeteranName', maxLength: 255 }),
        line_number: StringColumn({ label: 'LineNumber', maxLength: 255 }),
        award_name: StringColumn({ label: 'AwardName', maxLength: 255 }),
        award_code: StringColumn({ label: 'AwardCode', maxLength: 255 }),
        award_category: StringColumn({ label: 'AwardCategory', maxLength: 255 }),
        quantity: StringColumn({ label: 'Quantity', maxLength: 255 }),
        set_type: StringColumn({ label: 'SetType', maxLength: 255 }),
        devices: StringColumn({ label: 'Devices', maxLength: 255 }),
        device_count: StringColumn({ label: 'DeviceCount', maxLength: 255 }),
        engrave: StringColumn({ label: 'Engrave', maxLength: 255 }),
        engraving_text: StringColumn({ label: 'EngravingText', maxLength: 255 }),
        stock_number: StringColumn({ label: 'StockNumber', maxLength: 255 }),
        line_status: StringColumn({ label: 'LineStatus', maxLength: 255 }),
        backorder_eta: StringColumn({ label: 'BackorderETA', maxLength: 255 }),
        authority: StringColumn({ label: 'Authority', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        line_key: StringColumn({ label: 'LineKey', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-EngravingJob.csv → x_cog_mah_engraving_job (load order 70). */
export const x_cog_mah_stg_engraving_job = Table({
    name: 'x_cog_mah_stg_engraving_job',
    label: 'MAH Staging: vetmedals EngravingJob',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        job_number: StringColumn({ label: 'JobNumber', maxLength: 255 }),
        case_number: StringColumn({ label: 'CaseNumber', maxLength: 255 }),
        veteran_name: StringColumn({ label: 'VeteranName', maxLength: 255 }),
        job_status: StringColumn({ label: 'JobStatus', maxLength: 255 }),
        priority: StringColumn({ label: 'Priority', maxLength: 255 }),
        items: StringColumn({ label: 'Items', maxLength: 4000 }),
        engraving_text: StringColumn({ label: 'EngravingText', maxLength: 255 }),
        font: StringColumn({ label: 'Font', maxLength: 255 }),
        machine: StringColumn({ label: 'Machine', maxLength: 255 }),
        proof_checked: StringColumn({ label: 'ProofChecked', maxLength: 255 }),
        queued_date: StringColumn({ label: 'QueuedDate', maxLength: 255 }),
        started_date: StringColumn({ label: 'StartedDate', maxLength: 255 }),
        completed_date: StringColumn({ label: 'CompletedDate', maxLength: 255 }),
        engraver: StringColumn({ label: 'Engraver', maxLength: 255 }),
        rework_count: StringColumn({ label: 'ReworkCount', maxLength: 255 }),
        notes: StringColumn({ label: 'Notes', maxLength: 4000 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        days_in_queue: StringColumn({ label: 'DaysInQueue', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-ShipmentRecord.csv → x_cog_mah_shipment (load order 80). */
export const x_cog_mah_stg_shipment = Table({
    name: 'x_cog_mah_stg_shipment',
    label: 'MAH Staging: vetmedals ShipmentRecord',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        shipment_number: StringColumn({ label: 'ShipmentNumber', maxLength: 255 }),
        case_number: StringColumn({ label: 'CaseNumber', maxLength: 255 }),
        partial: StringColumn({ label: 'Partial', maxLength: 255 }),
        ship_to_name: StringColumn({ label: 'ShipToName', maxLength: 255 }),
        ship_to_street: StringColumn({ label: 'ShipToStreet', maxLength: 255 }),
        ship_to_city: StringColumn({ label: 'ShipToCity', maxLength: 255 }),
        ship_to_state: StringColumn({ label: 'ShipToState', maxLength: 255 }),
        ship_to_zip: StringColumn({ label: 'ShipToZIP', maxLength: 255 }),
        carrier: StringColumn({ label: 'Carrier', maxLength: 255 }),
        tracking_number: StringColumn({ label: 'TrackingNumber', maxLength: 255 }),
        ship_status: StringColumn({ label: 'ShipStatus', maxLength: 255 }),
        picked_date: StringColumn({ label: 'PickedDate', maxLength: 255 }),
        shipped_date: StringColumn({ label: 'ShippedDate', maxLength: 255 }),
        delivered_date: StringColumn({ label: 'DeliveredDate', maxLength: 255 }),
        contents: StringColumn({ label: 'Contents', maxLength: 255 }),
        piece_count: StringColumn({ label: 'PieceCount', maxLength: 255 }),
        weight_oz: StringColumn({ label: 'WeightOz', maxLength: 255 }),
        shipped_by: StringColumn({ label: 'ShippedBy', maxLength: 255 }),
        postage: StringColumn({ label: 'Postage', maxLength: 255 }),
        exception_note: StringColumn({ label: 'ExceptionNote', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        ship_date_text: StringColumn({ label: 'ShipDateText', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** vetmedals-CaseNote.csv → x_cog_mah_case_note (load order 90). */
export const x_cog_mah_stg_case_note = Table({
    name: 'x_cog_mah_stg_case_note',
    label: 'MAH Staging: vetmedals CaseNote',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        parent_case_number: StringColumn({ label: 'ParentCaseNumber', maxLength: 255 }),
        parent_unid_2: StringColumn({ label: 'ParentUNID (ParentUNID_2)', maxLength: 255 }),
        note_type: StringColumn({ label: 'NoteType', maxLength: 255 }),
        contact_name: StringColumn({ label: 'ContactName', maxLength: 255 }),
        contact_phone: StringColumn({ label: 'ContactPhone', maxLength: 255 }),
        body: StringColumn({ label: 'Body', maxLength: 4000 }),
        summary: StringColumn({ label: 'Summary', maxLength: 255 }),
        follow_up_date: StringColumn({ label: 'FollowUpDate', maxLength: 255 }),
        follow_up_done: StringColumn({ label: 'FollowUpDone', maxLength: 255 }),
        note_author: StringColumn({ label: 'NoteAuthor', maxLength: 255 }),
        note_date: StringColumn({ label: 'NoteDate', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        doc_authors: StringColumn({ label: 'DocAuthors', maxLength: 1000 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** heraldry-Request.csv → x_cog_mah_heraldry_request (load order 100). */
export const x_cog_mah_stg_heraldry_request = Table({
    name: 'x_cog_mah_stg_heraldry_request',
    label: 'MAH Staging: heraldry Request',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        document_number: StringColumn({ label: 'DocumentNumber', maxLength: 255 }),
        status: StringColumn({ label: 'Status', maxLength: 255 }),
        dodaac: StringColumn({ label: 'DODAAC', maxLength: 255 }),
        uic: StringColumn({ label: 'UIC', maxLength: 255 }),
        unit_name: StringColumn({ label: 'UnitName', maxLength: 255 }),
        rpd: StringColumn({ label: 'RPD', maxLength: 255 }),
        signal_code: StringColumn({ label: 'SignalCode', maxLength: 255 }),
        fund_code: StringColumn({ label: 'FundCode', maxLength: 255 }),
        project_code: StringColumn({ label: 'ProjectCode', maxLength: 255 }),
        supplementary_address: StringColumn({ label: 'SupplementaryAddress', maxLength: 255 }),
        request_type: StringColumn({ label: 'RequestType', maxLength: 255 }),
        required_delivery_date: StringColumn({ label: 'RequiredDeliveryDate', maxLength: 255 }),
        ship_to_dodaac: StringColumn({ label: 'ShipToDODAAC', maxLength: 255 }),
        ship_to_name: StringColumn({ label: 'ShipToName', maxLength: 255 }),
        ship_to_address1: StringColumn({ label: 'ShipToAddress1', maxLength: 255 }),
        ship_to_address2: StringColumn({ label: 'ShipToAddress2', maxLength: 255 }),
        ship_to_city: StringColumn({ label: 'ShipToCity', maxLength: 255 }),
        ship_to_state: StringColumn({ label: 'ShipToState', maxLength: 255 }),
        ship_to_zip: StringColumn({ label: 'ShipToZIP', maxLength: 255 }),
        justification: StringColumn({ label: 'Justification', maxLength: 4000 }),
        justification_text: StringColumn({ label: 'JustificationText', maxLength: 4000 }),
        line_count: StringColumn({ label: 'LineCount', maxLength: 255 }),
        total_value: StringColumn({ label: 'TotalValue', maxLength: 255 }),
        entered_date: StringColumn({ label: 'EnteredDate', maxLength: 255 }),
        entered_by: StringColumn({ label: 'EnteredBy', maxLength: 255 }),
        submitted_date: StringColumn({ label: 'SubmittedDate', maxLength: 255 }),
        reviewed_by: StringColumn({ label: 'ReviewedBy', maxLength: 255 }),
        approved_date: StringColumn({ label: 'ApprovedDate', maxLength: 255 }),
        vendor_key: StringColumn({ label: 'VendorKey', maxLength: 255 }),
        vendor_name: StringColumn({ label: 'VendorName', maxLength: 255 }),
        released_date: StringColumn({ label: 'ReleasedDate', maxLength: 255 }),
        released_by: StringColumn({ label: 'ReleasedBy', maxLength: 255 }),
        estimated_ship_date: StringColumn({ label: 'EstimatedShipDate', maxLength: 255 }),
        cancel_reason: StringColumn({ label: 'CancelReason', maxLength: 255 }),
        cancelled_date: StringColumn({ label: 'CancelledDate', maxLength: 255 }),
        cancelled_by: StringColumn({ label: 'CancelledBy', maxLength: 255 }),
        status_history: StringColumn({ label: 'StatusHistory', maxLength: 4000 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        doc_authors: StringColumn({ label: 'DocAuthors', maxLength: 1000 }),
        priority: StringColumn({ label: 'Priority', maxLength: 255 }),
        last_modified_by: StringColumn({ label: 'LastModifiedBy', maxLength: 255 }),
        last_modified_date: StringColumn({ label: 'LastModifiedDate', maxLength: 255 }),
        status_inquiry_key: StringColumn({ label: 'StatusInquiryKey', maxLength: 255 }),
        requester_name: StringColumn({ label: 'RequesterName', maxLength: 255 }),
        requester_rank: StringColumn({ label: 'RequesterRank', maxLength: 255 }),
        requester_role: StringColumn({ label: 'RequesterRole', maxLength: 255 }),
        requester_phone: StringColumn({ label: 'RequesterPhone', maxLength: 255 }),
        requester_email: StringColumn({ label: 'RequesterEmail', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** heraldry-RequestLine.csv → x_cog_mah_request_line (load order 110). */
export const x_cog_mah_stg_request_line = Table({
    name: 'x_cog_mah_stg_request_line',
    label: 'MAH Staging: heraldry RequestLine',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        parent_doc_number: StringColumn({ label: 'ParentDocNumber', maxLength: 255 }),
        line_number: StringColumn({ label: 'LineNumber', maxLength: 255 }),
        line_doc_number: StringColumn({ label: 'LineDocNumber', maxLength: 255 }),
        nsn: StringColumn({ label: 'NSN', maxLength: 255 }),
        item_key: StringColumn({ label: 'ItemKey', maxLength: 255 }),
        item_description: StringColumn({ label: 'ItemDescription', maxLength: 255 }),
        exception_data: StringColumn({ label: 'ExceptionData', maxLength: 4000 }),
        unit_of_issue: StringColumn({ label: 'UnitOfIssue', maxLength: 255 }),
        quantity: StringColumn({ label: 'Quantity', maxLength: 255 }),
        unit_price: StringColumn({ label: 'UnitPrice', maxLength: 255 }),
        extended_price: StringColumn({ label: 'ExtendedPrice', maxLength: 255 }),
        line_status: StringColumn({ label: 'LineStatus', maxLength: 255 }),
        vendor_ship_date: StringColumn({ label: 'VendorShipDate', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        vendor_key: StringColumn({ label: 'VendorKey', maxLength: 255 }),
        entered_by: StringColumn({ label: 'EnteredBy', maxLength: 255 }),
        lookup_key: StringColumn({ label: 'LookupKey', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})

/** heraldry-SESFlagRequest.csv → x_cog_mah_ses_flag_request (load order 120). */
export const x_cog_mah_stg_ses_flag_request = Table({
    name: 'x_cog_mah_stg_ses_flag_request',
    label: 'MAH Staging: heraldry SESFlagRequest',
    extends: 'sys_import_set_row',
    schema: {
        unid: StringColumn({ label: 'UNID', maxLength: 255 }),
        note_id: StringColumn({ label: 'NoteID', maxLength: 255 }),
        parent_unid: StringColumn({ label: 'ParentUNID', maxLength: 255 }),
        created: StringColumn({ label: 'Created', maxLength: 255 }),
        modified: StringColumn({ label: 'Modified', maxLength: 255 }),
        last_updated_by: StringColumn({ label: 'LastUpdatedBy', maxLength: 255 }),
        attachments: StringColumn({ label: 'Attachments', maxLength: 1000 }),
        ses_flag_number: StringColumn({ label: 'SESFlagNumber', maxLength: 255 }),
        status: StringColumn({ label: 'Status', maxLength: 255 }),
        executive_name: StringColumn({ label: 'ExecutiveName', maxLength: 255 }),
        executive_title: StringColumn({ label: 'ExecutiveTitle', maxLength: 255 }),
        executive_tier: StringColumn({ label: 'ExecutiveTier', maxLength: 255 }),
        organization: StringColumn({ label: 'Organization', maxLength: 255 }),
        flag_type: StringColumn({ label: 'FlagType', maxLength: 255 }),
        quantity: StringColumn({ label: 'Quantity', maxLength: 255 }),
        dodaac: StringColumn({ label: 'DODAAC', maxLength: 255 }),
        uic: StringColumn({ label: 'UIC', maxLength: 255 }),
        ship_to_address: StringColumn({ label: 'ShipToAddress', maxLength: 255 }),
        justification: StringColumn({ label: 'Justification', maxLength: 4000 }),
        entered_date: StringColumn({ label: 'EnteredDate', maxLength: 255 }),
        entered_by: StringColumn({ label: 'EnteredBy', maxLength: 255 }),
        approval_date: StringColumn({ label: 'ApprovalDate', maxLength: 255 }),
        approved_by: StringColumn({ label: 'ApprovedBy', maxLength: 255 }),
        return_reason: StringColumn({ label: 'ReturnReason', maxLength: 255 }),
        vendor_key: StringColumn({ label: 'VendorKey', maxLength: 255 }),
        released_date: StringColumn({ label: 'ReleasedDate', maxLength: 255 }),
        doc_readers: StringColumn({ label: 'DocReaders', maxLength: 1000 }),
        doc_authors: StringColumn({ label: 'DocAuthors', maxLength: 1000 }),
        status_inquiry_key: StringColumn({ label: 'StatusInquiryKey', maxLength: 255 }),
        mah_batch_id: StringColumn({ label: 'mah_batch_id', maxLength: 255 }),
        mah_source_row: StringColumn({ label: 'mah_source_row', maxLength: 255 }),
        mah_source_file: StringColumn({ label: 'mah_source_file', maxLength: 255 }),
    },
    allowWebServiceAccess: true,
})
