/**
 * Seed the cards of the metadata-created Visual Task Board(s).
 *
 * A guided board created in the UI gets its cards generated by the platform for every record that
 * matches its filter; a board that ships as application metadata (vtb_board + vtb_lane rows) starts
 * empty and, on this PDI, neither opening it nor inserting/updating matching records created cards.
 * Cards are plain `vtb_card` rows (board, lane, task, order), so this tool creates the missing ones
 * through the Table API — idempotent, one card per matching task, lane = the lane whose `value`
 * equals the task's lane field. Run after `npm run migrate` (or whenever jobs were loaded outside the UI).
 *
 *   npm run vtb-sync
 */
import { fileURLToPath } from 'node:url'
import { callInstance, type InstanceConfig, instanceFromEnv } from './lib/instance'

const BOARD_NAMES = ['MAH Native: engraving shop floor'] as const
const SAFE_QUERY = /^[A-Za-z0-9_=^:. -]+$/

interface Row {
    sys_id: string
    [field: string]: string | { value: string; link?: string } | undefined
}
interface TableResponse {
    result: Row[]
}

function ref(v: Row[string]): string {
    return typeof v === 'object' && v !== null ? v.value : String(v ?? '')
}

async function rows(cfg: InstanceConfig, table: string, query: string, fields: string, limit = 1000): Promise<Row[]> {
    if (!/^[a-z_]+$/.test(table) || !SAFE_QUERY.test(query)) throw new Error(`refusing unexpected query on ${table}`)
    const res = await callInstance<TableResponse>(cfg, {
        method: 'GET',
        path: `/api/now/table/${table}?sysparm_fields=${fields}&sysparm_limit=${limit}&sysparm_query=${encodeURIComponent(query)}`,
    })
    return res.result
}

export interface SyncSummary {
    board: string
    lanes: number
    matching: number
    created: number
    skipped: number
    unlaned: number
}

export async function syncBoard(cfg: InstanceConfig, boardName: string): Promise<SyncSummary> {
    const [board] = await rows(cfg, 'vtb_board', `name=${boardName}`, 'sys_id,table,field,filter')
    if (!board) throw new Error(`board not found: ${boardName}`)
    const table = ref(board.table)
    const field = ref(board.field)
    const lanes = await rows(cfg, 'vtb_lane', `board=${board.sys_id}`, 'sys_id,value,order')
    const laneByValue = new Map(lanes.map((l) => [ref(l.value), l.sys_id]))
    const tasks = await rows(cfg, table, `${ref(board.filter) || 'active=true'}^ORDERBYnumber`, `sys_id,number,${field}`)
    const cards = await rows(cfg, 'vtb_card', `board=${board.sys_id}^removed=false`, 'sys_id,task')
    const carded = new Set(cards.map((c) => ref(c.task)))
    const summary: SyncSummary = { board: boardName, lanes: lanes.length, matching: tasks.length, created: 0, skipped: 0, unlaned: 0 }
    let order = cards.length
    for (const t of tasks) {
        const lane = laneByValue.get(ref(t[field]))
        if (!lane) {
            summary.unlaned++
            continue
        }
        if (carded.has(t.sys_id)) {
            summary.skipped++
            continue
        }
        await callInstance(cfg, {
            method: 'POST',
            path: '/api/now/table/vtb_card',
            body: { board: board.sys_id, lane, task: t.sys_id, order: String(++order * 100) },
        })
        summary.created++
    }
    return summary
}

async function main(): Promise<void> {
    const cfg = instanceFromEnv()
    for (const name of BOARD_NAMES) {
        const s = await syncBoard(cfg, name)
        console.log(`${s.board}: lanes ${s.lanes}, matching tasks ${s.matching}, cards created ${s.created}, already present ${s.skipped}, no lane for value ${s.unlaned}`)
    }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
    main().catch((e: unknown) => {
        console.error(e instanceof Error ? e.message : String(e))
        process.exit(1)
    })
}
