import { EmailNotification } from '@servicenow/sdk/core'

// Replaces the legacy SendStatusMail agent. Case / request mail is event-driven from the
// lifecycle business rules; the aging mail is a record-driven notification on task_sla
// (has_breached becomes true on one of the MAH awards-case SLA definitions) — no MAH job.

export const caseStageChangedNotification = EmailNotification({
    $id: Now.ID['ntf_case_stage_changed'],
    table: 'x_cog_mah_native_awards_case',
    name: 'MAH Native Awards case stage changed',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah_native.case.stage_changed',
    },
    recipientDetails: {
        recipientFields: ['assigned_to', 'requester.email'],
        sendToCreator: false,
        isSubscribableByAllUsers: false,
    },
    emailContent: {
        subject: 'Awards case ${number} is now ${stage}',
        importance: 'low',
        messageHtml: `<p>Awards case <strong>\${number}</strong> for \${requester} has moved to the <strong>\${stage}</strong> stage (task state \${state}).</p>
<table cellpadding="4">
<tr><td>Source agency</td><td>\${source_agency}</td></tr>
<tr><td>Authorization date</td><td>\${authorization_date}</td></tr>
<tr><td>Award lines</td><td>\${line_count} (\${total_quantity} items)</td></tr>
<tr><td>Assigned to</td><td>\${assigned_to}</td></tr>
<tr><td>Opened</td><td>\${opened_at}</td></tr>
</table>
<p>This message was generated by MAH Case Management (Native). It contains no personally identifiable information beyond the requester name. Do not reply.</p>`,
    },
})

export const caseSlaBreachedNotification = EmailNotification({
    $id: Now.ID['ntf_case_sla_breached'],
    table: 'task_sla',
    name: 'MAH Native Awards case SLA breached',
    active: true,
    triggerConditions: {
        generationType: 'engine',
        onRecordInsert: false,
        onRecordUpdate: true,
        condition: 'has_breachedCHANGESTOtrue^task.sys_class_name=x_cog_mah_native_awards_case^sla.nameSTARTSWITHMAH Native awards case',
    },
    recipientDetails: {
        recipientFields: ['task.assigned_to', 'task.assignment_group'],
        sendToCreator: false,
    },
    emailContent: {
        subject: 'ACTION REQUIRED: ${task.number} breached ${sla} (${task.x_cog_mah_native_awards_case.stage})',
        importance: 'high',
        messageHtml: `<p>Awards case <strong>\${task.number}</strong> has breached the Task SLA <strong>\${sla}</strong>.</p>
<p>Started: \${start_time}<br/>
Breached: \${planned_end_time}<br/>
Business elapsed: \${business_percentage}%<br/>
Stage: \${task.state}</p>
<p>Please work or escalate this case. Generated by the platform SLA engine (task_sla) — there is no nightly aging job in this application.</p>`,
    },
})

export const requestSubmittedNotification = EmailNotification({
    $id: Now.ID['ntf_request_submitted'],
    table: 'x_cog_mah_native_heraldry_request',
    name: 'MAH Native Heraldry request submitted',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah_native.request.submitted',
    },
    recipientDetails: {
        recipientFields: ['submitted_by', 'reviewer'],
        eventParm1WithRecipient: true,
        sendToCreator: false,
    },
    emailContent: {
        subject: 'DD Form 1348-6 request ${number} (${document_number}) submitted',
        messageHtml: `<p>Heraldry request <strong>\${number}</strong> has been submitted for review.</p>
<table cellpadding="4">
<tr><td>Document number</td><td>\${document_number}</td></tr>
<tr><td>DODAAC / UIC</td><td>\${dodaac} / \${uic}</td></tr>
<tr><td>Requesting unit</td><td>\${requesting_unit}</td></tr>
<tr><td>Lines / total</td><td>\${line_count} / \${total_extended_price}</td></tr>
<tr><td>Required delivery</td><td>\${required_delivery_date}</td></tr>
</table>
<p>Review it in MAH Case Management (Native). Approval is requested from TACOM Awards Staff when the request enters review.</p>`,
    },
})

export const requestReleasedNotification = EmailNotification({
    $id: Now.ID['ntf_request_released'],
    table: 'x_cog_mah_native_heraldry_request',
    name: 'MAH Native Heraldry request released to vendor',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah_native.request.released',
    },
    recipientDetails: {
        recipientFields: ['company.x_cog_mah_native_poc_email', 'released_by'],
        sendToCreator: false,
    },
    emailContent: {
        subject: 'Heraldry request ${number} released to ${company}',
        importance: 'high',
        messageHtml: `<p>Request <strong>\${number}</strong> (\${document_number}) was released to <strong>\${company}</strong> on \${released_to_vendor}.</p>
<table cellpadding="4">
<tr><td>Lines</td><td>\${line_count}</td></tr>
<tr><td>Total extended price</td><td>\${total_extended_price}</td></tr>
<tr><td>Required delivery date</td><td>\${required_delivery_date}</td></tr>
<tr><td>Ship to</td><td>\${ship_to}</td></tr>
</table>
<p>The request header is now locked. Vendor users see this request under Heraldry requests (their own company only) and record acknowledgement and shipment there.</p>`,
    },
})

export const sesSubmittedNotification = EmailNotification({
    $id: Now.ID['ntf_ses_submitted'],
    table: 'x_cog_mah_native_ses_flag_request',
    name: 'MAH Native SES flag request submitted',
    active: true,
    triggerConditions: {
        generationType: 'event',
        eventName: 'x_cog_mah_native.ses.submitted',
    },
    recipientDetails: {
        recipientFields: ['assignment_group'],
        eventParm1WithRecipient: true,
        sendToCreator: false,
    },
    emailContent: {
        subject: 'SES flag request ${number} submitted for ${executive_name}',
        messageHtml: `<p>An SES positional flag request has been submitted.</p>
<table cellpadding="4">
<tr><td>Requesting office</td><td>\${requesting_office}</td></tr>
<tr><td>Executive</td><td>\${executive_name}, \${position_title}</td></tr>
<tr><td>Flag type / quantity</td><td>\${flag_type} x \${quantity}</td></tr>
</table>
<p>TACOM Awards Staff: approve or reject from the request form.</p>`,
    },
})
